# Generated by Django 5.2 on 2025-05-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_delivery_estimated_delivery_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
