# Generated by Django 5.2 on 2025-05-13 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_error_message_alter_payment_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format +2547XXXXXXXX or 2547XXXXXXXX.', regex='^\\+?2547[0-9]{8}$')]),
        ),
    ]
