# Generated by Django 5.2 on 2025-05-13 08:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_phone_number_order_payment_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='request_id',
            field=models.CharField(blank=True, help_text='Unique ID for the order request to prevent duplicates.', max_length=36, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['request_id'], name='orders_orde_request_bb9768_idx'),
        ),
    ]
