# Generated by Django 5.2 on 2025-05-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_request_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='request_id',
            field=models.CharField(blank=True, default='', help_text='Unique ID for the order request to prevent duplicates.', max_length=36, unique=True),
        ),
    ]
