# Generated by Django 5.2 on 2025-05-13 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='image',
        ),
    ]
