# Generated by Django 5.2 on 2025-05-23 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_branch'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name',)},
        ),
        migrations.RemoveField(
            model_name='product',
            name='branch',
        ),
    ]
